services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 7
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecommerce-server
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecommerce-client
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network: